linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - gofmt
    - goimports
  exclusions:
    paths:
      - examples/
run:
  timeout: 5m
