services:
  shark-socket-new:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "18000:18000"
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    restart: unless-stopped
