apiVersion: v1
kind: ConfigMap
metadata:
  name: shark-socket-config
  namespace: shark-socket
data:
  SHARK_TCP_ADDR: "0.0.0.0:18000"
  SHARK_METRICS_ADDR: "0.0.0.0:18080"
  SHARK_HEALTH_ADDR: "0.0.0.0:18081"
