apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shark-socket-hpa
  namespace: shark-socket
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shark-socket
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
