apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: tcp
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}
    - name: health
      port: {{ .Values.service.healthPort }}
      targetPort: {{ .Values.service.healthPort }}
