apiVersion: v1
kind: ConfigMap
metadata:
  name: shark-socket-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "shark-socket.labels" . | nindent 4 }}
data:
  config.json: |
    {
      "shutdown_timeout": {{ .Values.config.shutdownTimeout | quote }},
      "metrics_addr": {{ .Values.metrics.addr | quote }},
      "enable_metrics": {{ .Values.metrics.enabled }},
      "log_level": {{ .Values.config.logLevel | quote }}
    }
