apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shark-socket-http
  namespace: shark-socket
  labels:
    app.kubernetes.io/name: shark-socket
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shark-socket-http
                port:
                  number: 18400

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shark-socket-ws
  namespace: shark-socket
  labels:
    app.kubernetes.io/name: shark-socket
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/websocket-services: "shark-socket-ws"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: shark-socket-ws
                port:
                  number: 18600
