apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shark-socket

labels:
  - pairs:
      app.kubernetes.io/part-of: shark-socket
    includeSelectors: true

resources:
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - ../infra/prometheus/deployment.yaml
  - ../infra/prometheus/service.yaml
  - ../infra/prometheus/configmap.yaml
  - ingress.yaml
